### PR TITLE
Algebra pyret

### PR DESCRIPTION
**Pull request by jpolitz**
I don't think this is ready yet, but I want to get a nice UI up for discussing the changes I'm trying out in design-recipe-generator for Pyret programs.

### CODE REVIEW

**Comment by jpolitz** [comment]
To make sure I don't break backwards compatibility in existing stuff, my strategy is to add new !important css rules to override things when I need to, and put extra classes on Pyret stuff. Then the various design-recipe-generator functions take a #:lang option that defaults to 'racket and the same behavior that's always been there, and changes things if the language is 'pyret.

**Comment by jpolitz** [comment]
Only `racket build-workbook.rkt` works with algebra-pyret right now; I'm still working through unit stuff.

**Comment by sorawee** [comment]
Ughh. Sorry, I didn't mean to request for a review. That was an accident.

**Comment by jpolitz** [comment]
`racket build.rkt --course algebra-pyret` should work now, and units 1 and 2 have reasonable Pyret syntax and writing in them. I've adapted prose to smooth out how circles of evaluation work with infix syntax transitioning to functions; still working on that. After unit 2 things get much simpler to convert.

**Pull request merged**
