### PR TITLE
Algebra-Pyret Workbook and Online Activities + Solutions

### PR DESCRIPTION
**Pull request by doshiro**
Here is a sample of the student workbook: https://doshiro.github.io/curr/courses/algebra-pyret/en-us/resources/workbook/StudentWorkbook.pdf

The solutions to that workbook: [workbooksols.pdf](https://github.com/bootstrapworld/curr/files/2391045/workbooksols.pdf)

Here is the updated teacher resource page with links to unit activities and their solutions: https://doshiro.github.io/curr/courses/algebra-pyret/en-us/resources/teachers/index.shtml

### CODE REVIEW

**Comment by jpolitz** [comment]
@schanzer @kfisler could use a review not of content (I'll be the long-term maintainer of that) but that it builds for you, all the parameterization decisions don't seem wrong or scary, and when you generate the pages you don't get any weird broken links. From @doshiro 's link above it should be clear that algebra-pyret has basically the same structure as algebra.

@doshiro and I made a bunch of GDrive files for this owned by joe.politz@bootstrapworld.org; if there's a particular directory or place we should make those live, that would be good to move them to now, as well.

As far as putting this on the main site, I don't think anything prominent is needed -- I was thinking we could just link to this from the algebra page (e.g. "Also available in Pyret <link>").

**Comment by schanzer** [comment]
First off, this is awesome!! Some small formatting things that stick out to me:
- Can we have the DR pages (including fast functions) make `examples:`, `fun`, `if`, `else` and `end` bold?
- Not every contract has an octothorp before it, but they all should if we're making them comments? (this is in the workbook, the lesson plans, and some of the exercises)

**Comment by doshiro** [comment]
@schanzer In pyret, contracts are not comments; they are enforced! See the game starter code for an example of contract use in Pyret: https://code.pyret.org/editor#share=1xL3ZnWb43d5ih_fRib3dz3h8z9d__2om&v=f1d3c87

On that note, are there any contracts that do have the octothorp? I could change those. 

As for the bolding, I’ll look into it later today. 

Thanks for the feedback!

**Comment by doshiro** [comment]
The workbook how has bolded keywords in DRs!

**Comment by schanzer** [comment]
After our experience in Data Science, I'm not convinced that checked contracts are a good idea for introductory curricula like Algebra. @jpolitz , did you use these in PD? Are teachers using them with students? If they're working out, _awesome_. I just want to make sure we know they work before writing them into our materials.

**Comment by jpolitz** [comment]
In algebra, other parts of the syntax were much more difficult, and
contracts weren't a huge deal.

I think there are more types in Data Science, AND DS uses named arguments,
which is a whole other level of syntax.

When you had the issues with DS contracts, were you writing

is-old-cat :: (animal :: Row) -> Boolean

or were you writing

is-old-cat :: Row -> Boolean


I think the former causes quite a bit more pain, but makes a lot of sense
for DS code beause "animal" is quite descriptive while Row is not.

On September 21, 2018 at 9:07:16 AM, Emmanuel Schanzer (
notifications@github.com) wrote:

After our experience in Data Science, I'm not convinced that checked
contracts are a good idea for introductory curricula like Algebra. @jpolitz
<https://github.com/jpolitz> , did you use these in PD? Are teachers using
them with students? If they're working out, *awesome*. I just want to make
sure we know they work before writing them into our materials.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bootstrapworld/curr/pull/428#issuecomment-423587794>,
or mute the thread

**Comment by schanzer** [comment]
Good point. OK, I'm happy with this as it stands. Merging.

**Comment by doshiro** [comment]
Glad to see this get merged! Thanks @schanzer !!

**Pull request merged**
